# This Python2 script extracts the final geometries in xyz format (xyz - Å) from gamess MP2 thermochem outputs (cartesian - AU) - by Alistair King
# the cartesian (AU) outputs are simply scaled by 0.5291817 to convert to Å
# www.helsinki.fi/cellulose-chemistry

import sys
import os

for filename in sys.argv[1:]:
	
	lines =[]
	file = open(filename, 'r')
	for line in file: 
        	lines.append(line)  

	xyzfile = open(filename + '.xyz', 'w')

	file = open(filename, 'r')
	filestr = file.read()

	if filestr.find('ONE-ELECTRON') == -1:
		print filename + ' contains errors and was skipped'
		
	else:	
		str = lines.pop(-1)
		while 'ONE-ELECTRON' not in str:
			str = lines.pop(-1)

		else:
			str = lines.pop(-1)
			str = str.strip()
			noatoms = str[0:2]
			noatoms = noatoms.strip()
			print ''
			print ''
			print ''
			print ''
			print(filename + '.xyz') 
			print ''
			print noatoms
			print 'Geometry generated by gamess-xyz-extract.py'
			xyzfile.write(noatoms)
			xyzfile.write('\n')
			xyzfile.write('Generated by gamess-xyz-extract.py  --  www.helsinki.fi/cellulose-chemistry \n')
			xyz = str[2:]
			xyz = xyz.strip()
			print xyz
			xyzlist = xyz.split()
			atom = xyzlist.pop(0)
			xyzfile.write(atom)
			xyzfile.write('      ')
			x = round(0.5291817 * float(xyzlist.pop(0)), 10)
			xyzfile.write(`x`)
			xyzfile.write('      ')
			y = round(0.5291817 * float(xyzlist.pop(0)), 10)
			xyzfile.write(`y`)
			xyzfile.write('      ')
			z = round(0.5291817 * float(xyzlist.pop(0)), 10)
			xyzfile.write(`z`)
			xyzfile.write('\n')
			str = lines.pop(-1)
			str = str.strip()
			noatoms = str[0:2]
			noatoms = noatoms.strip()
			if noatoms != "":
				counter = int(noatoms) - 1
				while counter >= 0:
					xyz = str[2:]
					xyz = xyz.strip()
					print xyz
					xyzlist = xyz.split()
					atom = xyzlist.pop(0)
					xyzfile.write(atom)
					xyzfile.write('      ')
					x = round(0.5291817 * float(xyzlist.pop(0)), 10)
					xyzfile.write(`x`)
					xyzfile.write('      ')
					y = round(0.5291817 * float(xyzlist.pop(0)), 10)
					xyzfile.write(`y`)
					xyzfile.write('      ')
					z = round(0.5291817 * float(xyzlist.pop(0)), 10)
					xyzfile.write(`z`)
					xyzfile.write('\n')
					str = lines.pop(-1)
					str = str.strip()
					noatoms = str[0:2]
					noatoms = noatoms.strip()
					counter = counter -1
		xyzfile.close()
		
		



